import axios from './axios.js'

export const getVideos = (pageNum, pageSize) => axios.get('/videos/' + pageNum + '/' + pageSize)
export const getVideoById = (id) => axios.get('/videos/' + id)
export const getVideosById = (userId, pageNum, pageSize) => axios.get('/videos/userid/' + userId + '/' + pageNum + '/' + pageSize)
export const getVideosByUserAndTitle = (userId, title) => axios.get('/videos/keyword/' + userId + '/' + title)
export const getVideosBykeyword = (content) => axios.get('/videos/keyword?content=' + content)
export const getCollectionVideos = (userId, pageNum, pageSize) => axios.get('/videos/collection/' + userId + '/' + pageNum + '/' + pageSize)
export const addViews = (video) => axios.put('/videos', video)
export const addStars = (video) => axios.put('/videos', video)
export const addCollections = (params) => axios.post('/videos/collection', params)
export const deleteVideo = (id) => axios.delete('/videos/' + id)
export const uploadImg = (formData) => axios.post('/videos/img', formData)
export const uploadVideo = (formData) => axios.post('/videos', formData)
export const uploadVideoInfo = (video) => axios.post('/videos/info', video)
export const getVideoTypes = () => axios.get('/videotypes')
